### ISSUE TITLE
Add support for a Java 11 Jenkins image

### ISSUE THREAD

**Issue by eldada** [odavid/my-bloody-jenkins#132] opened 2019-02-24 15:03 UTC
As a user of this (awesome) project, I'd like to be able and opt for using the more advanced Jenkins with Java 11 image.
As described in https://jenkins.io/blog/2018/12/14/java11-preview-availability/, it's already possible.

It would be a great feature to allow users to opt for the java 11 preview image.

**Comment by odavid** [comment] 2019-02-24 15:27
Thanks @eldada!

My Bloody Jenkins is based on jenkins LTS by design. The current LTS is 2.150.3 and the java11 support only *starts* from 2.155 version. 
Until Jenkins will release a new LTS, it will be hard for me to add this kind of support.

Also the current version is based on alpine, but the JDK11 jenkins image is based on stretch. 
I will try to work on multiple distributions of the image soon (e.g. alpine and stretch).

Regards,
Ohad

**Comment by eldada** [comment] 2019-02-28 19:48
Great @odavid! Looking forward. I'll leave this open for tracking.

**Comment by odavid** [comment] 2019-03-15 07:05
@eldada - released [2.164.1-113](https://github.com/odavid/my-bloody-jenkins/blob/master/CHANGELOG.md#21641-113)

Image will be available in few min in Docker hub.

Closing this issue.

**Closed by odavid** 2019-03-15 07:05 UTC
